services:
  grott:
    container_name: grott
    image: ledidobe/grottserver:beta
    volumes:
      - ./grott/output:/tmp/grottlog/
      - ./grott/config/grott.ini:/app/grott.ini
      - ./grott/config/grott.ini:/grott.ini
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 5279:5279
      - 5781:5781
      - 5782:5782
    restart: unless-stopped
    environment:
      - TZ=Europe/London
      - PYTHONUNBUFFERED=1
      - gblockcmd=True
      - gincludeall=True
    network_mode: host
