[Generic]
verbose = True
#mode = server
invtype = sph
decrypt = True
# Worked but had semi regular 3-6 min and a few 40+ min gaps (11 server restarts)
#blockcmd = True
blockcmd = False
noipf = True
tmzone = Europe/London
minrecl = 20
responsewait = 1
timeout = 28
keepalive = 60
# Force the grottserver engine to also output parsed JSON blocks
gshmfile = False
gshmqsub = True

[Growatt]
#ip = 47.91.67.66
ip = 127.0.0.1
#ip = 0.0.0.0
#port = 5279
port = 5781

[MQTT]
nomqtt = False
#ip = 192.168.86.250
ip = 127.0.0.1
port = 1883
topic = energy/growatt
auth = False

[PVOutput]
[influx]

[extension]
# Enable the extension to hijack the routing loop
#extension = True
#extname = grottext
