version: '3' 

services:
  homeassistant:
    container_name: home-assistant 
    image: lscr.io/linuxserver/homeassistant:latest
    volumes:
      - ./config:/config
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    restart: unless-stopped
    network_mode: host
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
