services:
  mylar:
    image: ghcr.io/linuxserver/mylar
    container_name: mylar
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
      - /media/big_boi/Books/Comics:/comics
      - /media/big_boi/Books/Downloads:/downloads
    ports:
      - 8090:8090
    restart: unless-stopped
