services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=sradams.co.uk
      - VALIDATION=dns
      - SUBDOMAINS=homeassistant
      - DNSPLUGIN=cloudflare
      - EMAIL=me@sradams.co.uk
      - ONLY_SUBDOMAINS=true
    volumes:
      - ./config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks:
      - proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy:
    driver: bridge
