version: "3.6"
services:

  plexms:
    container_name: plexms
    restart: always
    network_mode: host
    ports:
      - 32400:32400
      - 32400:32400/udp
      - 32469:32469
      - 32469:32469/udp
      - 5353:5353/udp
      - 1900:1900/udp
    image: linuxserver/plex:latest
    volumes:
      - /media/small_boi/docker/plexms:/config
      - /media/big_boi/Movies:/movies
      - /media/big_boi/Music:/music
      - /media/big_boi/Photos:/photos
      - /media/big_boi/TV:/TV1
      - /media/full_boi/TV:/TV2
      - /media/small_boi/Users:/user_data
    env_file:
      - docker.env
    environment:
      - VERSION=docker
      - PUID={PUID}
      - PGID={PGID}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
