version: "3.6"
services:

  calibre:
    image: linuxserver/calibre:latest
    container_name: calibre
    environment:
      - PUID={PUID}
      - PGID={PGID}
      - TZ=Europe/London
    volumes:
      - /media/BigSlave/Books:/config
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped
