version: "3.7"

services:
  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    network_mode: host
    volumes:
      - node-red-data:/data

volumes:
  node-red-data:
